---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.6.0-jdk-8-alpine

run:
  path: "mvn"
  args:
    - -f
    - spring-boot-service/pom.xml
    - clean
    - compile
    - test