---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox
    tag: latest

run:
  path: "sh"
  args:
    - ls

# run:
#   path: "mvn"
#   args:
#     - -f
#     - spring-boot-service/pom.xml
#     - clean
#     - compile
#     - test